### PR TITLE
use regular stat() instead of non-standard __xstat64 abi

### LINKED ISSUE #7455: Alpine 3.19 + Java 8: Symbol not found: __xstat64
## steps

Running sbt with java 8 on alpine 3.19 fails due to java.lang.UnsatisfiedLinkError.
Try to invoke sbt when running on alpine 3.19, e.g. using docker:

```
docker run --rm -it alpine:3.19
# inside the container:
apk add openjdk8 bash
cd $(mktemp -d)
# download sbt
wget https://github.com/sbt/sbt/releases/download/v1.9.7/sbt-1.9.7.tgz
tar -xzf sbt-1.9.7.tgz
# create example project (crash)
yes "" | sbt/bin/sbt new scala/hello-world.g8
```

## problem

sbt can't be run when using java 8 and latest musl libc. All invocations fail with the following stacktrace:
```
/tmp/tmp.aJhdoP # yes "" | sbt/bin/sbt new scala/hello-world.g8
[info] [launcher] getting org.scala-sbt sbt 1.9.7  (this may take some time)...
[info] [launcher] getting Scala 2.12.18 (for sbt)...
java.lang.UnsatisfiedLinkError: Error looking up function '__xstat64': Symbol not found: __xstat64
        at com.sun.jna.Function.<init>(Function.java:252)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:620)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:596)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:582)
        at com.sun.jna.Library$Handler.invoke(Library.java:248)
        at com.sun.proxy.$Proxy0.__xstat64(Unknown Source)
        at sbt.internal.io.Linux64Milli$.$anonfun$getModifiedTimeNative$1(Milli.scala:215)
        at sbt.internal.io.MilliPosixBase.checkedIO(Milli.scala:100)
        at sbt.internal.io.Linux64Milli$.getModifiedTimeNative(Milli.scala:215)
        at sbt.internal.io.Linux64Milli$.getModifiedTimeNative(Milli.scala:210)
        at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:65)
        at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:387)
        at sbt.io.IO$.$anonfun$getModifiedTimeOrZero$1(IO.scala:1436)
        at sbt.internal.io.Retry$.apply$mJc$sp(Retry.scala:47)
        at sbt.internal.io.Retry$.apply$mJc$sp(Retry.scala:29)
        at sbt.internal.io.Retry$.apply$mJc$sp(Retry.scala:24)
        at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1436)
        at sbt.internal.classpath.ClassLoaderCache$Key$$anonfun$$lessinit$greater$3.apply(ClassLoaderCache.scala:59)
        at sbt.internal.classpath.ClassLoaderCache$Key$$anonfun$$lessinit$greater$3.apply(ClassLoaderCache.scala:59)
        at scala.collection.immutable.List.map(List.scala:293)
        at sbt.internal.classpath.ClassLoaderCache$Key.<init>(ClassLoaderCache.scala:59)
        at sbt.internal.classpath.ClassLoaderCache$Key.<init>(ClassLoaderCache.scala:60)
        at sbt.internal.classpath.ClassLoaderCache.cachedCustomClassloader(ClassLoaderCache.scala:195)
        at sbt.State$StateOpsImpl$.initializeClassLoaderCache$extension(State.scala:417)
        at sbt.StandardMain$.initialState(Main.scala:286)
        at sbt.xMain$.$anonfun$run$9(Main.scala:112)
        at sbt.io.IO$.withTemporaryDirectory(IO.scala:496)
        at sbt.io.IO$.withTemporaryDirectory(IO.scala:506)
        at sbt.xMain$.run(Main.scala:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
        at sbt.xMain.run(Main.scala:47)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.UnsatisfiedLinkError: Error looking up function '__xstat64': Symbol not found: __xstat64
```

## expectation

Builds using java 8 on latest alpine release should be possible.

## notes

When using Java 11 (`openjdk11-jdk`) / Java 17 (`openjdk17-jdk`) / Java 21 (`openjdk21-jdk`), everything is fine.
When using alpine:3.18, everything is fine too.

### PR DESCRIPTION
**Pull request by bratkartoffel**
This should fix sbt/sbt#7455

@eed3si9n 

Disclaimer: I'm not a scala developer, nor have I experience with JNA. I'd be glad if someone else could verify / review this thoroughly.

### CODE REVIEW

File: io/src/main/scala/sbt/internal/io/Milli.scala [hunk 1]
```diff
@@ -205,28 +205,28 @@ private abstract class PosixMilliIntUtim[Interface <: Utimensat[Int]: ClassTag]
...
-  def __xstat64(version: Int, filePath: String, buf: Linux64FileStat): Int
+  def stat(filePath: String, buf: Linux64FileStat): Int
 }
 private object Linux64Milli extends PosixMilliLongUtim[Linux64] {
   protected final val AT_FDCWD: Int = -100
   protected final val UTIME_OMIT: Long = (1L << 30) - 2
   protected def getModifiedTimeNative(filePath: String) = {
     val stat = new Linux64FileStat
-    checkedIO(filePath) { libc.__xstat64(1, filePath, stat) }
+    checkedIO(filePath) { libc.stat(filePath, stat) }
```
Comment (eed3si9n) [inline io/src/main/scala/sbt/internal/io/Milli.scala:215]: LGTM

**Review by eed3si9n — APPROVED** [review]

**Comment by bratkartoffel** [comment]
I've made a silly typo, so I had to amend & force push again, sorry

**Comment by bratkartoffel** [comment]
The mimaReportBinaryIssues fails as the abi calls changed. How can I fix this?

**Comment by eed3si9n** [comment]
Plz add

```scala
exclude[DirectMissingMethodProblem]("sbt.internal.io.Linux32.*"),
exclude[ReversedMissingMethodProblem]("sbt.internal.io.Linux32.*"),
exclude[DirectMissingMethodProblem]("sbt.internal.io.Linux64.*"),
exclude[ReversedMissingMethodProblem]("sbt.internal.io.Linux64.*"),
```

around https://github.com/sbt/io/blob/develop/build.sbt#L136

**Comment by bratkartoffel** [comment]
After digging a bit, i stumbled accross #211 (Native Milli code no longer necessary on JDK10 or greater)

As mentioned in the description, the whole code was added due to a bug in the JVM. The underlying issue was not only fixed for Java 10 (as stated in the PR description), but also backported to Java 8u301. So I think, this whole stuff is no longer needed at all.

See also https://www.oracle.com/java/technologies/javase/8u301-relnotes.html

**Comment by eed3si9n** [comment]
> but also backported to Java 8u301

I didn't know that. I'd be happy to see this whole thing dropped. https://github.com/sbt/io/blob/develop/io/src/main/scala/sbt/io/JavaMilli.scala is public, but the rest of internal stuff can probably go.

**Comment by bratkartoffel** [comment]
I'd be glad to help, but this is far beyond my scala knowledge.
Maybe just merge this MR as a "hotfix" and drop the whole stuff later?
