### PR TITLE
avoid exposing private type in API

### LINKED ISSUE #209: API exposes private type
# Description
A bunch of methods in `Using` have `OpenFile[T]` as their return type, which is private.
 # How to reproduce
View the `sbt.io.Using` class in scaladoc and look at e.g. `fileInputStream`.
# Expected behaviour
The type should be more descriptive. It took me a while to figure out that it was a subtype of `Using[File, T]`, so I reckon changing the exposed type could improve UX. I don't know if there's a particular reason.

This would break binary compatibility.

### PR DESCRIPTION
**Pull request by bbjubjub2494**
Fix #209. breaks binary compatibility.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=pull/210/head&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1255/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-develop-pull/210/head-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1255/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@4c553835a0dcc44c7228322fb2d3b95eeed17578
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@9bef954753a1ae033722d5bc9e89b945a9f2da3e
  io                | <A HREF="https://github.com/sbt/io/pull/210">pull/210/head       </A> | sbt/io@6a1a47c77e784a5e033d2fc585f3294c777ae98d
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@91071253d98e66331a7821278444ebf41544da20
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@2e0d2d920a9f11c1910f0a5d48a2ff6f2c57c44d

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=develop&io=pull/210/head&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by bbjubjub2494** [comment]
Maybe a [use case] simplified signature could be used between now and the next binary-incompatible release?

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1259/console">is in progress...</a>

File: io/src/main/scala/sbt/io/Using.scala [hunk 1]
```diff
@@ -69,9 +69,9 @@ object Using {
       def close(s: T) = closeF(s)
     }
 
-  def file[T <: AutoCloseable](openF: File => T): OpenFile[T] = file(openF, closeCloseable)
+  def file[T <: AutoCloseable](openF: File => T): Using[File, T] = file(openF, closeCloseable)
```
Comment (eed3si9n) [inline io/src/main/scala/sbt/io/Using.scala:72]: What would be the downstream impact here?
If someone wrote `val x = Using.file(...)` in their plugin, would this change cause runtime issue?

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-develop-pull/210/head-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1259/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@4c553835a0dcc44c7228322fb2d3b95eeed17578
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@9bef954753a1ae033722d5bc9e89b945a9f2da3e
  io                | <A HREF="https://github.com/sbt/io/pull/210">pull/210/head       </A> | sbt/io@6a1a47c77e784a5e033d2fc585f3294c777ae98d
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@91071253d98e66331a7821278444ebf41544da20
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@2e0d2d920a9f11c1910f0a5d48a2ff6f2c57c44d

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=develop&io=pull/210/head&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by eed3si9n** [comment]
In https://jenkins.scala-sbt.org:8592/job/sbt-validator/1259/consoleFull, Dbuild is reporting that this will cause

```
[sbt212:error] java.lang.StackOverflowError
[sbt212:error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:814)
[sbt212:error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:814)
...
```

during

```
[sbt212] [error] Error during tests:
[sbt212] [error] 	sbt.internal.util.SettingsTest
```

I am kind of confused why this is the case.

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1262/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-develop-pull/210/head-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1262/">has checked</A> the following projects, tested using sbt-allsources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@4c553835a0dcc44c7228322fb2d3b95eeed17578
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@9bef954753a1ae033722d5bc9e89b945a9f2da3e
  io                | <A HREF="https://github.com/sbt/io/pull/210">pull/210/head       </A> | sbt/io@6a1a47c77e784a5e033d2fc585f3294c777ae98d
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@91071253d98e66331a7821278444ebf41544da20
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@2e0d2d920a9f11c1910f0a5d48a2ff6f2c57c44d

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=develop&io=pull/210/head&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1263/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-develop-pull/210/head~-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1263/">has checked</A> the following projects, tested using sbt-allsources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@4c553835a0dcc44c7228322fb2d3b95eeed17578
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@9bef954753a1ae033722d5bc9e89b945a9f2da3e
  io                | <A HREF="https://github.com/sbt/io/pull/210/head~">pull/210/head~      </A> | sbt/io@ca872a2561ee918e65a062569637a7e3261267a4
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@91071253d98e66331a7821278444ebf41544da20
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@2e0d2d920a9f11c1910f0a5d48a2ff6f2c57c44d

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=develop&io=pull/210/head~&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

File: io/src/main/scala/sbt/io/Using.scala (hunk 1 above)
Comment (bbjubjub2494) [reply io/src/main/scala/sbt/io/Using.scala:72]: If the plugin isn't recompiled we get a linking error when loading the class. I think that's expected tho:
```
java.lang.NoSuchMethodError: sbt.io.Using$.file(Lscala/Function1;Lscala/Function1;)Lsbt/io/OpenFile;
```

As far as source-level compatibility goes, I'm not even sure it's possible to construct code that would break due to this. We return the same object with a looser static type, so this can only lead to type errors. What I could think of is using a mutable reference:
```
var x = Using.file(...)
x = new Using[File, _] { ... }
```
but this works after the change and not before. (because type inference types `x` as `OpenFile` and thus rejects `Using` objects). I have no formal proof, but since OpenFile is private outside code cannot reference it directly, and it has no public methods that Using doesn't have so I'm pretty confident it should be fine honestly.

**Comment by bbjubjub2494** [comment]
Rebased onto develop, I seemed to have missed some recent commits for unknown reasons.

File: io/src/main/scala/sbt/io/Using.scala (hunk 1 above)
Comment (eed3si9n) [reply io/src/main/scala/sbt/io/Using.scala:72]: > If the plugin isn't recompiled we get a linking error when loading the class. 

sbt 1 is published with Semantic Versioning, so we intend to support all plugins published against sbt 1.0 to work throughout the 1.x series. We can create a branch for sbt 2.0, so we'll remember to merge it in the future.

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1265/console">is in progress...</a>

File: io/src/main/scala/sbt/io/Using.scala (hunk 1 above)
Comment (bbjubjub2494) [reply io/src/main/scala/sbt/io/Using.scala:72]: Got it. If that's the rule, then so be it. ~~Would you be OK with the `@usecase` solution I mentioned above? That would help the initial issue and could be a transitional fix until 2.0 comes around. (which I will target in another PR)~~

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-develop-pull/210/merge-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1265/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@4c553835a0dcc44c7228322fb2d3b95eeed17578
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@9bef954753a1ae033722d5bc9e89b945a9f2da3e
  io                | <A HREF="https://github.com/sbt/io/pull/210/merge">pull/210/merge      </A> | 
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@91071253d98e66331a7821278444ebf41544da20
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@2e0d2d920a9f11c1910f0a5d48a2ff6f2c57c44d

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=develop&io=pull/210/merge&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1266/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-develop-pull/210/head-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1266/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@4c553835a0dcc44c7228322fb2d3b95eeed17578
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@9bef954753a1ae033722d5bc9e89b945a9f2da3e
  io                | <A HREF="https://github.com/sbt/io/pull/210">pull/210/head       </A> | sbt/io@c4f6dc7b83101acb8726bc8184f5b40bb3bc4be3
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@91071253d98e66331a7821278444ebf41544da20
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@2e0d2d920a9f11c1910f0a5d48a2ff6f2c57c44d

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=develop&io=pull/210/head&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by bbjubjub2494** [comment]
Well it seems like I learned the hard way that `@usecase` is a terrible idea and already deprecated. (See https://github.com/scala/scala-dev/issues/584) It chokes on `val`s and on defaulted parameters, so I can't make it work on all the definitions I would like to. Let's not do that.

As it stands, this PR targets 2.0.

**Comment by eed3si9n** [comment]
I'll create a branch to track this for future merge.
