### PR TITLE
Wait 1s before testing for file contents change

### LINKED ISSUE #82: PollingWatchService fails to detect file changes...
While investigating https://github.com/sbt/sbt/issues/3687 I found that `PollingWatchService` is really broken: it doesn't detect modified files.. o_O

I'll submit a PR that adds a pending test to the test suite.

### PR DESCRIPTION
**Pull request by dwijnand**
Looks like on some filesystems, like HFS+, time stamp granularity is only 1 second
https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/APFS_Guide/VolumeFormatComparison/VolumeFormatComparison.html
therefore in order to notice a last modified time change you need to
have elapsed into the next second. We'll do this by sleeping 1 second.

Fixes #82

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?io=pull/102/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by eed3si9n** [comment]
```
[info] - should detect modified files *** FAILED ***
[info]   false was not equal to true (SourceModificationWatchSpec.scala:320)
```

**Comment by dwijnand** [comment]
Damn... it failed on Travis CI like it had before: https://github.com/sbt/io/pull/84#issuecomment-346317581

I was hoping @cunei's Milli fix would've fix this.. @cunei any ideas?

File: io/src/test/scala/sbt/internal/io/SourceModificationWatchSpec.scala [hunk 1]
```diff
@@ -319,4 +326,17 @@ abstract class SourceModificationWatchSpec(
     WatchState.empty(service, sources).withCount(1)
   }
 
+  private def supportsSubSecondModifiedTime(dir: File) = {
+    val file = File.createTempFile("", "", dir)
```
Comment (cunei) [inline io/src/test/scala/sbt/internal/io/SourceModificationWatchSpec.scala]: Travis says "Prefix string too short"

Comment (dwijnand) [reply io/src/test/scala/sbt/internal/io/SourceModificationWatchSpec.scala]: 🙄

File: io/src/test/scala/sbt/internal/io/PollingWatchServiceSpec.scala [hunk 2]
```diff
@@ -1,12 +1,13 @@
...
 import scala.concurrent.duration._
 
 class PollingWatchServiceSpec
     extends SourceModificationWatchSpec(
       new PollingWatchService(500.milliseconds),
       500.milliseconds,
       3.seconds
-    )
+    ) {
+  Milli.getMilliSupportDiagnostic(IO.temporaryDirectory) map println
```
Comment (cunei) [inline io/src/test/scala/sbt/internal/io/PollingWatchServiceSpec.scala]: This should really be the project dir; the temporary directory on *nix is typically on /tmp, which is tmpfs, a virtual ram-based file system. So, it's not really checking the file system at all.

Comment (cunei) [reply io/src/test/scala/sbt/internal/io/PollingWatchServiceSpec.scala]: Same for the `createTempFile()`, below

Comment (dwijnand) [reply io/src/test/scala/sbt/internal/io/PollingWatchServiceSpec.scala]: Good point..

**Comment by dwijnand** [comment]
This is now green, so it's ready for review.

**Review by eed3si9n — APPROVED** [review]
